// S314 Package A: shade sail fabric colors (GALE Pacific Commercial 95) and post powder-coat colors
// (Cardinal Industrial Finishes). Every number, code and official name below traces to an official
// manufacturer source read on 2026-09-18 (see SOURCES); nothing is estimated except the swatch hex,
// which is an approximate screen color whose sampling method is recorded per item. Generated from
// /tmp/s314/colors/{gen_sails,gen_posts,emit_ts}.py on the AIR; edit the data here, not the UI.

export const SOURCES = {
  galeProfile: "GALE Pacific, Commercial 95 Product Profile Rev.18 08/23 (per-colour values tested to AS 4174:2018). The profile Josh sent as a screenshot; full copy read at backyardcity.com/Images/GPU/Comm95-Specs.pdf.",
  galeProfileCurrent: "GALE Pacific, current Commercial NinetyFive Product Profile on galecommercial.com (userfiles/files/Product Profiles/GALE Commercial - Product Profile - Commercial NinetyFive - 16-3-27.pdf). Same UVR block, UVE, cover and shade factor values as Rev.18 except where noted.",
  galeBrochure: "GALE Pacific, Commercial NinetyFive 340 brochure (Standard & Flame Retardant, InDesign PDF dated 2023-10-17, ~/Downloads/Commercial_NinetyFive_Brochure.pdf): colour chart with two codes per colour, 340 gsm, 15-year UV warranty badge for Standard.",
  cardinalCard: "Cardinal Powder Coatings stock color card, Summer 2024: the sheet Josh shows customers (photos IMG_2488.heic and IMG_2489.heic). Name and code as printed; finish, gloss, cure and powder type decoded from the code with the card's own Powder Coating Product Number Identification key; footnotes (*, **, square) quoted from the card.",
  cardinalShop: "Cardinal Paint online store, shop.cardinalpaint.com (powder-coating collection variant lists), used to cross-check names and codes. cardinalpaint.com itself could not be fetched (robots.txt: self-signed certificate), so no values come from it.",
} as const;

/** General facts that apply to every Commercial 95 colour (not per colour). */
export const SAIL_FABRIC = {
  product: "GALE Pacific Commercial 95 (340 gsm knitted HDPE shade fabric)",
  warranty: "15-year UV degradation warranty on the fabric (Standard, all colours)",
  warrantyShort: "15 years",
  fabricShort: "340 gsm knitted HDPE",
  testStandard: "AS 4174:2018",
  source: SOURCES.galeProfile,
} as const;

export type SailColor = {
  id: string;
  /** Customer-facing name (GALE's own names are already plain, so they are reused). */
  friendlyName: string;
  officialName: string;
  /** Standard (non-FR) code from the GALE chart. */
  code: string;
  /** Flame-retardant version code from the GALE chart (printed in the FR orange). */
  frCode: string;
  hex: string;
  /** Two-tone knit (only Rivergum); rendered as fine stripes. */
  stripes?: [string, string];
  uvrBlock: string;
  shadeFactor: string;
  uvrTransmission: string;
  uvVisTransmission: string;
  coverFactor: string;
  uve: string;
  protection: string;
  statLine: string;
  source: string;
  swatch: string;
};

const SAIL_SWATCH = "Linear-light mean of GALE's official digital swatch image in the Commercial NinetyFive 340 brochure PDF (approximate on screen).";

export const SAIL_COLORS: SailColor[] = [
  {
    id: "white",
    friendlyName: "White",
    officialName: "White",
    code: "497736",
    frCode: "495732",
    hex: "#EAEEED",
    uvrBlock: "92.9%",
    shadeFactor: "73.9%",
    uvrTransmission: "7.1%",
    uvVisTransmission: "26.1%",
    coverFactor: "93%",
    uve: "92%",
    protection: "Very Effective",
    statLine: "92.9% UV block · 73.9% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "natural",
    friendlyName: "Natural",
    officialName: "Natural",
    code: "445003",
    frCode: "495541",
    hex: "#E0DDD0",
    uvrBlock: "93.1%",
    shadeFactor: "76.2%",
    uvrTransmission: "6.9%",
    uvVisTransmission: "23.8%",
    coverFactor: "93%",
    uve: "92%",
    protection: "Very Effective",
    statLine: "93.1% UV block · 76.2% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "desert-sand",
    friendlyName: "Desert Sand",
    officialName: "Desert Sand",
    code: "444983",
    frCode: "495565",
    hex: "#B08C63",
    uvrBlock: "93.8%",
    shadeFactor: "86.1%",
    uvrTransmission: "6.2%",
    uvVisTransmission: "13.9%",
    coverFactor: "94%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "93.8% UV block · 86.1% shade factor",
    source: SOURCES.galeProfile + " The current galecommercial.com profile text reads 68.1 for Desert Sand shade factor, which breaks its own row (100 minus 13.9% UV-vis transmission = 86.1); Rev.18 prints 86.1, used here.",
    swatch: SAIL_SWATCH,
  },
  {
    id: "driftwood",
    friendlyName: "Driftwood",
    officialName: "Driftwood",
    code: "502294",
    frCode: "502348",
    hex: "#9E908B",
    uvrBlock: "94.9%",
    shadeFactor: "90.0%",
    uvrTransmission: "5.1%",
    uvVisTransmission: "10.0%",
    coverFactor: "95%",
    uve: "94%",
    protection: "Very Effective",
    statLine: "94.9% UV block · 90.0% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "stone",
    friendlyName: "Stone",
    officialName: "Stone",
    code: "502300",
    frCode: "502355",
    hex: "#A09B99",
    uvrBlock: "94.3%",
    shadeFactor: "89.3%",
    uvrTransmission: "5.7%",
    uvVisTransmission: "10.7%",
    coverFactor: "94%",
    uve: "94%",
    protection: "Very Effective",
    statLine: "94.3% UV block · 89.3% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "steel-grey",
    friendlyName: "Steel Grey",
    officialName: "Steel Grey",
    code: "445041",
    frCode: "495718",
    hex: "#969191",
    uvrBlock: "94.3%",
    shadeFactor: "90.9%",
    uvrTransmission: "5.7%",
    uvVisTransmission: "9.1%",
    coverFactor: "94%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "94.3% UV block · 90.9% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "gun-metal",
    friendlyName: "Gun Metal",
    officialName: "Gun Metal",
    code: "455262",
    frCode: "495527",
    hex: "#5E5E5E",
    uvrBlock: "93.2%",
    shadeFactor: "91.4%",
    uvrTransmission: "6.8%",
    uvVisTransmission: "8.6%",
    coverFactor: "93%",
    uve: "92%",
    protection: "Very Effective",
    statLine: "93.2% UV block · 91.4% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "charcoal",
    friendlyName: "Charcoal",
    officialName: "Charcoal",
    code: "444969",
    frCode: "495558",
    hex: "#363E45",
    uvrBlock: "93.4%",
    shadeFactor: "93.1%",
    uvrTransmission: "6.6%",
    uvVisTransmission: "6.9%",
    coverFactor: "93%",
    uve: "91%",
    protection: "Very Effective",
    statLine: "93.4% UV block · 93.1% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "black",
    friendlyName: "Black",
    officialName: "Black",
    code: "444945",
    frCode: "495640",
    hex: "#242424",
    uvrBlock: "94.8%",
    shadeFactor: "94.6%",
    uvrTransmission: "5.2%",
    uvVisTransmission: "5.4%",
    coverFactor: "94%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "94.8% UV block · 94.6% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "yellow",
    friendlyName: "Yellow",
    officialName: "Yellow",
    code: "445072",
    frCode: "495619",
    hex: "#D9A82D",
    uvrBlock: "95.5%",
    shadeFactor: "77.6%",
    uvrTransmission: "4.5%",
    uvVisTransmission: "22.4%",
    coverFactor: "95%",
    uve: "94%",
    protection: "Very Effective",
    statLine: "95.5% UV block · 77.6% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "orange",
    friendlyName: "Orange",
    officialName: "Orange",
    code: "459215",
    frCode: "495633",
    hex: "#E8652E",
    uvrBlock: "94.0%",
    shadeFactor: "80.6%",
    uvrTransmission: "6.0%",
    uvVisTransmission: "19.4%",
    coverFactor: "93%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "94.0% UV block · 80.6% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "cherry-red",
    friendlyName: "Cherry Red",
    officialName: "Cherry Red",
    code: "444976",
    frCode: "495695",
    hex: "#AD272A",
    uvrBlock: "91.2%",
    shadeFactor: "78.4%",
    uvrTransmission: "8.8%",
    uvVisTransmission: "21.6%",
    coverFactor: "91%",
    uve: "91%",
    protection: "Very Effective",
    statLine: "91.2% UV block · 78.4% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "deep-ochre",
    friendlyName: "Deep Ochre",
    officialName: "Deep Ochre",
    code: "444990",
    frCode: "495688",
    hex: "#663432",
    uvrBlock: "94.6%",
    shadeFactor: "92.8%",
    uvrTransmission: "5.4%",
    uvVisTransmission: "7.2%",
    coverFactor: "94%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "94.6% UV block · 92.8% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "rivergum",
    friendlyName: "Rivergum",
    officialName: "Rivergum",
    code: "445027",
    frCode: "495589",
    hex: "#8C8E6A",
    stripes: ["#BAAE83", "#667758"],
    uvrBlock: "92.9%",
    shadeFactor: "88.7%",
    uvrTransmission: "7.1%",
    uvVisTransmission: "11.3%",
    coverFactor: "93%",
    uve: "92%",
    protection: "Very Effective",
    statLine: "92.9% UV block · 88.7% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "bright-green",
    friendlyName: "Bright Green",
    officialName: "Bright Green",
    code: "459208",
    frCode: "495596",
    hex: "#449C50",
    uvrBlock: "92.5%",
    shadeFactor: "88.6%",
    uvrTransmission: "7.5%",
    uvVisTransmission: "11.4%",
    coverFactor: "92%",
    uve: "91%",
    protection: "Very Effective",
    statLine: "92.5% UV block · 88.6% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "brunswick-green",
    friendlyName: "Brunswick Green",
    officialName: "Brunswick Green",
    code: "444952",
    frCode: "495572",
    hex: "#364546",
    uvrBlock: "94.7%",
    shadeFactor: "93.8%",
    uvrTransmission: "5.3%",
    uvVisTransmission: "6.2%",
    coverFactor: "94%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "94.7% UV block · 93.8% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "aquamarine",
    friendlyName: "Aquamarine",
    officialName: "Aquamarine",
    code: "502287",
    frCode: "502331",
    hex: "#33B0A4",
    uvrBlock: "95.1%",
    shadeFactor: "89.5%",
    uvrTransmission: "4.9%",
    uvVisTransmission: "10.5%",
    coverFactor: "95%",
    uve: "95%",
    protection: "Most Effective",
    statLine: "95.1% UV block · 89.5% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "bluebird",
    friendlyName: "Bluebird",
    officialName: "Bluebird",
    code: "502263",
    frCode: "502317",
    hex: "#0E8CB4",
    uvrBlock: "95.3%",
    shadeFactor: "91.2%",
    uvrTransmission: "4.7%",
    uvVisTransmission: "8.8%",
    coverFactor: "95%",
    uve: "95%",
    protection: "Most Effective",
    statLine: "95.3% UV block · 91.2% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "sky-blue",
    friendlyName: "Sky Blue",
    officialName: "Sky Blue",
    code: "445034",
    frCode: "495626",
    hex: "#5A7882",
    uvrBlock: "92.2%",
    shadeFactor: "89.0%",
    uvrTransmission: "7.8%",
    uvVisTransmission: "11.0%",
    coverFactor: "92%",
    uve: "91%",
    protection: "Very Effective",
    statLine: "92.2% UV block · 89.0% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "turquoise",
    friendlyName: "Turquoise",
    officialName: "Turquoise",
    code: "445065",
    frCode: "495664",
    hex: "#09607C",
    uvrBlock: "91.5%",
    shadeFactor: "86.0%",
    uvrTransmission: "8.5%",
    uvVisTransmission: "14.0%",
    coverFactor: "92%",
    uve: "91%",
    protection: "Very Effective",
    statLine: "91.5% UV block · 86.0% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "aquatic-blue",
    friendlyName: "Aquatic Blue",
    officialName: "Aquatic Blue",
    code: "444938",
    frCode: "495671",
    hex: "#2D458A",
    uvrBlock: "91.1%",
    shadeFactor: "85.6%",
    uvrTransmission: "8.9%",
    uvVisTransmission: "14.4%",
    coverFactor: "92%",
    uve: "91%",
    protection: "Very Effective",
    statLine: "91.1% UV block · 85.6% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
  {
    id: "navy-blue",
    friendlyName: "Navy Blue",
    officialName: "Navy Blue",
    code: "445010",
    frCode: "495602",
    hex: "#2B3247",
    uvrBlock: "94.4%",
    shadeFactor: "93.6%",
    uvrTransmission: "5.6%",
    uvVisTransmission: "6.4%",
    coverFactor: "94%",
    uve: "93%",
    protection: "Very Effective",
    statLine: "94.4% UV block · 93.6% shade factor",
    source: SOURCES.galeProfile,
    swatch: SAIL_SWATCH,
  },
];

export type PostSurface = "Smooth" | "Hammer" | "Pearlescent" | "Texture" | "Metallic" | "Hammertone" | "Vein" | "Wrinkle" | "Special";

export type PostColor = {
  id: string;
  friendlyName: string;
  /** Name exactly as printed on the Cardinal card. */
  officialName: string;
  code: string;
  group: PostGroupId;
  hex: string;
  /** Code digit 3 (Surface Appearance). */
  surface: PostSurface;
  /** Code digit 4 (Gloss), as the key prints it. */
  gloss: string;
  /** Code digit 4 as a number 0 to 9, for the sheen meter. */
  glossLevel: number;
  /** Code digit 2 (Cure / UV Resistance). */
  cure: string;
  /** Code letter 1 (Product Type). */
  powder: string;
  /** The card's footnote for this color, quoted. */
  cardinalNote?: string;
  statLine: string;
  source: string;
  swatch: string;
};

export type PostGroupId = "reds" | "browns" | "hammer" | "superdurable" | "beiges" | "whites" | "blacks" | "grays" | "specialty";

export const POST_GROUPS: { id: PostGroupId; title: string }[] = [
  { id: "reds", title: "Reds, oranges and yellows" },
  { id: "browns", title: "Browns, greens and blues" },
  { id: "hammer", title: "Hammer finishes" },
  { id: "superdurable", title: "Superdurable" },
  { id: "beiges", title: "Beiges and mauves" },
  { id: "whites", title: "Whites" },
  { id: "blacks", title: "Blacks" },
  { id: "grays", title: "Grays" },
  { id: "specialty", title: "Specialty finishes" },
];

const POST_SWATCH = "Median of this swatch in Josh's photo of the card (IMG_2489, Display P3 converted to sRGB), white-balanced to the card's white paper between swatches. Approximate: cardinalpaint.com digital swatches could not be fetched.";

export const POST_COLORS: PostColor[] = [
  {
    id: "p009-rd02",
    friendlyName: "Dark Red",
    officialName: "Dark Red 90 Gloss",
    code: "P009-RD02",
    group: "reds",
    hex: "#A52C39",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-rd03",
    friendlyName: "Classic Red",
    officialName: "Red 90 Gloss",
    code: "T009-RD03",
    group: "reds",
    hex: "#B8273A",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t241-rd129",
    friendlyName: "Red Texture",
    officialName: "Red Texture",
    code: "T241-RD129",
    group: "reds",
    hex: "#BE4754",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-rd01",
    friendlyName: "Bright Red",
    officialName: "Red 90 Gloss",
    code: "T009-RD01",
    group: "reds",
    hex: "#D52E41",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-og26",
    friendlyName: "International Orange",
    officialName: "International Orange 90 Gloss",
    code: "T009-OG26",
    group: "reds",
    hex: "#D84B3B",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-og01",
    friendlyName: "Safety Orange",
    officialName: "Safety Orange 90 Gloss",
    code: "T009-OG01",
    group: "reds",
    hex: "#F56938",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-yl71",
    friendlyName: "Golden Yellow",
    officialName: "Yellow 90 Gloss",
    code: "T009-YL71",
    group: "reds",
    hex: "#F99D00",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-yl14",
    friendlyName: "Amber Yellow",
    officialName: "FS 13538 Yellow 90 Gloss",
    code: "T009-YL14",
    group: "reds",
    hex: "#F5A000",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-yl01",
    friendlyName: "Lemon Yellow",
    officialName: "Yellow 90 Gloss",
    code: "T009-YL01",
    group: "reds",
    hex: "#FBDA1C",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c209-yl130",
    friendlyName: "Tractor Yellow",
    officialName: "Tractor Yellow 90 Gloss",
    code: "C209-YL130",
    group: "reds",
    hex: "#CA954A",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c209-br358",
    friendlyName: "Terra Brown",
    officialName: "RAL 8028 Terra Brown 90 Gloss",
    code: "C209-BR358",
    group: "browns",
    hex: "#625449",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p004-br23",
    friendlyName: "Bronze",
    officialName: "Bronze 40 Gloss",
    code: "P004-BR23",
    group: "browns",
    hex: "#525351",
    surface: "Smooth",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t032-br62",
    friendlyName: "Brown Texture",
    officialName: "Brown Texture",
    code: "T032-BR62",
    group: "browns",
    hex: "#4B4C4F",
    surface: "Texture",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p000-gn264",
    friendlyName: "Olive Drab Green",
    officialName: "FS 34094 OD Green Flat",
    code: "P000-GN264",
    group: "browns",
    hex: "#5D6A63",
    surface: "Smooth",
    gloss: "0 to 7",
    glossLevel: 0,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 0 to 7",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t007-gn16",
    friendlyName: "Traffic Green",
    officialName: "Traffic Green 70 Gloss",
    code: "T007-GN16",
    group: "browns",
    hex: "#485051",
    surface: "Smooth",
    gloss: "70 (±5)",
    glossLevel: 7,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 70",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t007-gn13",
    friendlyName: "Highway Green",
    officialName: "FS 14066 D.O.T Green 70 Gloss",
    code: "T007-GN13",
    group: "browns",
    hex: "#2B594E",
    surface: "Smooth",
    gloss: "70 (±5)",
    glossLevel: 7,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 70",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c006-gn03",
    friendlyName: "Dark Green",
    officialName: "Green 60 Gloss",
    code: "C006-GN03",
    group: "browns",
    hex: "#364B49",
    surface: "Smooth",
    gloss: "60 (±5)",
    glossLevel: 6,
    cure: "Exterior/400°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 60",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c209-gn411",
    friendlyName: "Tractor Green",
    officialName: "Tractor Green 90 Gloss",
    code: "C209-GN411",
    group: "browns",
    hex: "#407A4F",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bl544",
    friendlyName: "Royal Blue Texture",
    officialName: "Blue Texture",
    code: "C241-BL544",
    group: "browns",
    hex: "#4967AB",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t032-bl04",
    friendlyName: "Gray Blue Texture",
    officialName: "FS 25109 Blue Texture",
    code: "T032-BL04",
    group: "browns",
    hex: "#647C94",
    surface: "Texture",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-bl01",
    friendlyName: "Bright Blue",
    officialName: "Blue 90 Gloss",
    code: "T009-BL01",
    group: "browns",
    hex: "#214FA4",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-bl05",
    friendlyName: "Azure Blue",
    officialName: "Blue 90 Gloss",
    code: "T009-BL05",
    group: "browns",
    hex: "#0077D5",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t008-bl20",
    friendlyName: "Navy Blue",
    officialName: "Dark Blue 80 Gloss",
    code: "T008-BL20",
    group: "browns",
    hex: "#384B6C",
    surface: "Smooth",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bl210",
    friendlyName: "Slate Blue Texture",
    officialName: "Blue Texture",
    code: "C241-BL210",
    group: "browns",
    hex: "#637A9B",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c013-gr08",
    friendlyName: "Gray Hammer",
    officialName: "Gray Hammer",
    code: "C013-GR08",
    group: "hammer",
    hex: "#848793",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester HAA",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-bg38",
    friendlyName: "Beige Hammer",
    officialName: "Beige Hammer",
    code: "T013-BG38",
    group: "hammer",
    hex: "#EBE4D5",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t012-wh260",
    friendlyName: "Warm White Hammer",
    officialName: "White Hammer",
    code: "T012-WH260",
    group: "hammer",
    hex: "#F0F2F2",
    surface: "Hammer",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-wh09",
    friendlyName: "Bright White Hammer",
    officialName: "White Hammer",
    code: "T013-WH09",
    group: "hammer",
    hex: "#E9F0F8",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-bl468",
    friendlyName: "Blue Hammer",
    officialName: "Blue Hammer",
    code: "T013-BL468",
    group: "hammer",
    hex: "#3D5BA2",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-rd15",
    friendlyName: "Red Hammer",
    officialName: "Red Hammer",
    code: "T013-RD15",
    group: "hammer",
    hex: "#C14261",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-gn220",
    friendlyName: "Green Hammer",
    officialName: "Green Hammer",
    code: "T013-GN220",
    group: "hammer",
    hex: "#49535D",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t012-br161",
    friendlyName: "Bronze Hammer",
    officialName: "Bronze Hammer",
    code: "T012-BR161",
    group: "hammer",
    hex: "#68656E",
    surface: "Hammer",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-bk62",
    friendlyName: "Black Hammer",
    officialName: "Black Hammer",
    code: "T013-BK62",
    group: "hammer",
    hex: "#575862",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t013-gr185",
    friendlyName: "Light Gray Hammer",
    officialName: "RAL 7035 Light Grey Hammer",
    code: "T013-GR185",
    group: "hammer",
    hex: "#CFD2D3",
    surface: "Hammer",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammer · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t902-bk208",
    friendlyName: "Superdurable Matte Black",
    officialName: "Black Superdurable 20 Gloss",
    code: "T902-BK208",
    group: "superdurable",
    hex: "#383940",
    surface: "Smooth",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c909-wh485",
    friendlyName: "Superdurable White",
    officialName: "White Superdurable 90 Gloss",
    code: "C909-WH485",
    group: "superdurable",
    hex: "#F9FAF8",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p009-bk180",
    friendlyName: "Superdurable Gloss Black",
    officialName: "Black Superdurable 90 Gloss",
    code: "P009-BK180",
    group: "superdurable",
    hex: "#27292F",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card names it Superdurable but the code's second digit (0) decodes to Exterior/400°F.",
    swatch: POST_SWATCH,
  },
  {
    id: "t905-bk505",
    friendlyName: "Superdurable Satin Black",
    officialName: "Black Superdurable 50 Gloss",
    code: "T905-BK505",
    group: "superdurable",
    hex: "#292A2F",
    surface: "Smooth",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t909-ral1023",
    friendlyName: "Traffic Yellow",
    officialName: "Traffic Yellow Superdurable 90 Gloss",
    code: "T909-RAL1023",
    group: "superdurable",
    hex: "#FFCE00",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c909-rd203",
    friendlyName: "Superdurable Red",
    officialName: "Red Superdurable 90 Gloss",
    code: "C909-RD203",
    group: "superdurable",
    hex: "#BC3646",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card prints C909-RD203; shop.cardinalpaint.com lists T909-RD203.",
    swatch: POST_SWATCH,
  },
  {
    id: "c909-yl201",
    friendlyName: "Superdurable Yellow",
    officialName: "Yellow Superdurable 90 Gloss",
    code: "C909-YL201",
    group: "superdurable",
    hex: "#FCD843",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card prints C909-YL201; shop.cardinalpaint.com lists T909-YL201.",
    swatch: POST_SWATCH,
  },
  {
    id: "c909-og201",
    friendlyName: "Superdurable Orange",
    officialName: "Orange Superdurable 90 Gloss",
    code: "C909-OG201",
    group: "superdurable",
    hex: "#ED673B",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card prints C909-OG201; shop.cardinalpaint.com lists T909-OG201.",
    swatch: POST_SWATCH,
  },
  {
    id: "t909-ral5005",
    friendlyName: "Signal Blue",
    officialName: "Signal Blue Superdurable 90 Gloss",
    code: "T909-RAL5005",
    group: "superdurable",
    hex: "#234990",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t909-ral6017",
    friendlyName: "May Green",
    officialName: "May Green Superdurable 90 Gloss",
    code: "T909-RAL6017",
    group: "superdurable",
    hex: "#638E5B",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t909-ral9003",
    friendlyName: "Signal White",
    officialName: "Signal White Superdurable 90 Gloss",
    code: "T909-RAL9003",
    group: "superdurable",
    hex: "#F2F1EC",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t909-ral9005",
    friendlyName: "Jet Black",
    officialName: "Jet Black Superdurable 90 Gloss",
    code: "T909-RAL9005",
    group: "superdurable",
    hex: "#292E33",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Superdurable/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-bg01",
    friendlyName: "Almond",
    officialName: "Almond 90 Gloss",
    code: "T009-BG01",
    group: "beiges",
    hex: "#EDE0CA",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p000-bg631",
    friendlyName: "Desert Sand",
    officialName: "FS 33446 Desert Sand Flat",
    code: "P000-BG631",
    group: "beiges",
    hex: "#BEA78B",
    surface: "Smooth",
    gloss: "0 to 7",
    glossLevel: 0,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 0 to 7",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bg218",
    friendlyName: "Putty Texture",
    officialName: "Putty Texture",
    code: "C241-BG218",
    group: "beiges",
    hex: "#CFCBBB",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t032-bg03",
    friendlyName: "Beige Texture",
    officialName: "Beige Texture",
    code: "T032-BG03",
    group: "beiges",
    hex: "#D0CCBC",
    surface: "Texture",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t241-bg137",
    friendlyName: "Beige Fine Texture",
    officialName: "Beige Texture",
    code: "T241-BG137",
    group: "beiges",
    hex: "#EAE6D8",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p009-bg02",
    friendlyName: "Beige",
    officialName: "Beige 90 Gloss",
    code: "P009-BG02",
    group: "beiges",
    hex: "#E1D4B7",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-bg16",
    friendlyName: "Designer Beige",
    officialName: "Designer Beige 90 Gloss",
    code: "T009-BG16",
    group: "beiges",
    hex: "#D3BFA3",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bg296",
    friendlyName: "Light Mauve Texture",
    officialName: "Light Mauve Texture",
    code: "C241-BG296",
    group: "beiges",
    hex: "#AA9F9A",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr557",
    friendlyName: "Dark Mauve Texture",
    officialName: "Dark Mauve Texture",
    code: "C241-GR557",
    group: "beiges",
    hex: "#ADA2A5",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t031-wh06",
    friendlyName: "Pearl White Texture",
    officialName: "Pearl White Texture",
    code: "T031-WH06",
    group: "whites",
    hex: "#D3D2C5",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t032-wh15",
    friendlyName: "White Texture",
    officialName: "White Texture",
    code: "T032-WH15",
    group: "whites",
    hex: "#F9F8EC",
    surface: "Texture",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-wh13",
    friendlyName: "Cool White",
    officialName: "White 90 Gloss",
    code: "T009-WH13",
    group: "whites",
    hex: "#EBEAEF",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p009-wh14",
    friendlyName: "Ice White",
    officialName: "White 90 Gloss",
    code: "P009-WH14",
    group: "whites",
    hex: "#ECEEF4",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p005-wh01",
    friendlyName: "Satin White",
    officialName: "FS 27875 White 50 Gloss",
    code: "P005-WH01",
    group: "whites",
    hex: "#F9FAF6",
    surface: "Smooth",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t002-wh08",
    friendlyName: "Matte White",
    officialName: "White 20 Gloss",
    code: "T002-WH08",
    group: "whites",
    hex: "#FEFEFF",
    surface: "Smooth",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p009-wh04",
    friendlyName: "Classic White",
    officialName: "White 90 Gloss",
    code: "P009-WH04",
    group: "whites",
    hex: "#F6F6F5",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-wh11",
    friendlyName: "Bright White",
    officialName: "White 90 Gloss",
    code: "T009-WH11",
    group: "whites",
    hex: "#FFFFFF",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card name is faint; name from the card cover (White Gloss T009-WH11) and the shop (White 90%).",
    swatch: POST_SWATCH,
  },
  {
    id: "t009-wh12",
    friendlyName: "High Reflective White",
    officialName: "High Reflective White 90 Gloss",
    code: "T009-WH12",
    group: "whites",
    hex: "#FFFFFF",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card name is faint; name from shop.cardinalpaint.com (High Reflective White 90%).",
    swatch: POST_SWATCH,
  },
  {
    id: "t007-wh121",
    friendlyName: "Semi-Gloss White",
    officialName: "White 70 Gloss",
    code: "T007-WH121",
    group: "whites",
    hex: "#F9FAFC",
    surface: "Smooth",
    gloss: "70 (±5)",
    glossLevel: 7,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 70",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c209-wh486",
    friendlyName: "Soft White",
    officialName: "LC White 90 Gloss",
    code: "C209-WH486",
    group: "whites",
    hex: "#FBFBFC",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c209-wh492",
    friendlyName: "Pure White",
    officialName: "RAL 9010 Pure White 90 Gloss",
    code: "C209-WH492",
    group: "whites",
    hex: "#F8F4EC",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-wh493",
    friendlyName: "Pure White Texture",
    officialName: "RAL 9010 Pure White Texture",
    code: "C241-WH493",
    group: "whites",
    hex: "#F3EEE9",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard + " Card print is faint (reads WH493 or WH495); code taken from shop.cardinalpaint.com (C241-WH493).",
    swatch: POST_SWATCH,
  },
  {
    id: "c209-wh490",
    friendlyName: "Gray White",
    officialName: "RAL 9002 Grey White 90 Gloss",
    code: "C209-WH490",
    group: "whites",
    hex: "#F4F5F5",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card name is faint; matches shop.cardinalpaint.com (RAL 9002 Gray-White).",
    swatch: POST_SWATCH,
  },
  {
    id: "c031-wh120",
    friendlyName: "Matte White Texture",
    officialName: "White Texture",
    code: "C031-WH120",
    group: "whites",
    hex: "#FFFFFF",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t004-wh453",
    friendlyName: "Platinum White",
    officialName: "Platinum White",
    code: "T004-WH453",
    group: "whites",
    hex: "#F3F2F5",
    surface: "Smooth",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bk303",
    friendlyName: "Fine Texture Black",
    officialName: "Black Fine Texture",
    code: "C241-BK303",
    group: "blacks",
    hex: "#36383D",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bk01",
    friendlyName: "Textured Black",
    officialName: "Black Texture",
    code: "C241-BK01",
    group: "blacks",
    hex: "#2F3135",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t241-bk59",
    friendlyName: "Textured Black",
    officialName: "Black Texture",
    code: "T241-BK59",
    group: "blacks",
    hex: "#2E3034",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t041-bk179",
    friendlyName: "Textured Black",
    officialName: "Black Texture",
    code: "T041-BK179",
    group: "blacks",
    hex: "#303238",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t041-bk215",
    friendlyName: "Slip Resistant Black",
    officialName: "Slip Resistant Black",
    code: "T041-BK215",
    group: "blacks",
    hex: "#34373D",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bk110",
    friendlyName: "Fine Texture Black",
    officialName: "Black Fine Texture",
    code: "C241-BK110",
    group: "blacks",
    hex: "#37393F",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-bk109",
    friendlyName: "Coarse Texture Black",
    officialName: "Black Texture",
    code: "C241-BK109",
    group: "blacks",
    hex: "#32363B",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p000-bk247",
    friendlyName: "Flat Black",
    officialName: "FS 37038 Black Flat",
    code: "P000-BK247",
    group: "blacks",
    hex: "#3D414B",
    surface: "Smooth",
    gloss: "0 to 7",
    glossLevel: 0,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 0 to 7",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t001-bk120",
    friendlyName: "Matte Black",
    officialName: "Black 10 Gloss",
    code: "T001-BK120",
    group: "blacks",
    hex: "#2F333C",
    surface: "Smooth",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t002-bk08",
    friendlyName: "Low Sheen Black",
    officialName: "FS 27038 Black 20 Gloss",
    code: "T002-BK08",
    group: "blacks",
    hex: "#272C34",
    surface: "Smooth",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p004-bk02",
    friendlyName: "Satin Black",
    officialName: "Black 40 Gloss",
    code: "P004-BK02",
    group: "blacks",
    hex: "#252932",
    surface: "Smooth",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t005-bk78",
    friendlyName: "Semi-Gloss Black",
    officialName: "Black 50 Gloss",
    code: "T005-BK78",
    group: "blacks",
    hex: "#2B3038",
    surface: "Smooth",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t006-bk05",
    friendlyName: "Semi-Gloss Black",
    officialName: "Black 60 Gloss",
    code: "T006-BK05",
    group: "blacks",
    hex: "#292D34",
    surface: "Smooth",
    gloss: "60 (±5)",
    glossLevel: 6,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 60",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c206-bk266",
    friendlyName: "Semi-Gloss Black",
    officialName: "Black 60 Gloss",
    code: "C206-BK266",
    group: "blacks",
    hex: "#23272F",
    surface: "Smooth",
    gloss: "60 (±5)",
    glossLevel: 6,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Smooth · Gloss 60",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t008-bk181",
    friendlyName: "Gloss Black",
    officialName: "Black 80+ Gloss",
    code: "T008-BK181",
    group: "blacks",
    hex: "#21252E",
    surface: "Smooth",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-bk12",
    friendlyName: "High Gloss Black",
    officialName: "FS 17038 Black 90 Gloss",
    code: "T009-BK12",
    group: "blacks",
    hex: "#1F232B",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard + " Card print reads FS 17308; shop.cardinalpaint.com lists #17038 (FS 17038), used here.",
    swatch: POST_SWATCH,
  },
  {
    id: "p003-gr01",
    friendlyName: "Satin Gray",
    officialName: "FS 26307 Gray 30 Gloss",
    code: "P003-GR01",
    group: "grays",
    hex: "#9C9D9A",
    surface: "Smooth",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p004-gr09",
    friendlyName: "Medium Gray",
    officialName: "ANSI 49 Gray 40 Gloss",
    code: "P004-GR09",
    group: "grays",
    hex: "#7D8489",
    surface: "Smooth",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p004-gr16",
    friendlyName: "Satin Light Gray",
    officialName: "ANSI 61 Gray 40 Gloss",
    code: "P004-GR16",
    group: "grays",
    hex: "#93999B",
    surface: "Smooth",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "p008-gr21",
    friendlyName: "Dark Gray",
    officialName: "RAL 7042 Grey 80 Gloss",
    code: "P008-GR21",
    group: "grays",
    hex: "#9C9EA3",
    surface: "Smooth",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/400°F",
    powder: "Polyurethane",
    statLine: "Smooth · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t238-gr2069",
    friendlyName: "Premium Gray",
    officialName: "FS 16081 Premium Gray",
    code: "T238-GR2069",
    group: "grays",
    hex: "#4A5057",
    surface: "Texture",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t238-gr2070",
    friendlyName: "Light Gray",
    officialName: "RAL 7035 Light Gray",
    code: "T238-GR2070",
    group: "grays",
    hex: "#CECFCE",
    surface: "Texture",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr484",
    friendlyName: "Dark Gray Texture",
    officialName: "Dark Gray Texture",
    code: "C241-GR484",
    group: "grays",
    hex: "#3C434D",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr85",
    friendlyName: "Telephone Gray",
    officialName: "Telephone Gray Texture",
    code: "C241-GR85",
    group: "grays",
    hex: "#A6A9A8",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr487",
    friendlyName: "Pale Gray Texture",
    officialName: "PMS 427C Grey Texture",
    code: "C241-GR487",
    group: "grays",
    hex: "#D2D3D5",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr483",
    friendlyName: "Slate Gray Texture",
    officialName: "PMS 431C Gray Texture",
    code: "C241-GR483",
    group: "grays",
    hex: "#6E747F",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr07",
    friendlyName: "Granite Texture",
    officialName: "Gray Texture",
    code: "C241-GR07",
    group: "grays",
    hex: "#6F6F74",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t241-gr142",
    friendlyName: "Light Gray Fine Texture",
    officialName: "Light Gray Texture",
    code: "T241-GR142",
    group: "grays",
    hex: "#D6D7D2",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t241-gr851",
    friendlyName: "Light Gray Texture",
    officialName: "RAL 7035 Light Gray Texture",
    code: "T241-GR851",
    group: "grays",
    hex: "#CCCDCE",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard + " Card prints T241-GR851; shop.cardinalpaint.com lists C241-GR851.",
    swatch: POST_SWATCH,
  },
  {
    id: "t008-gr736",
    friendlyName: "Gloss Light Gray",
    officialName: "ANSI 61 Gray 80 Gloss",
    code: "T008-GR736",
    group: "grays",
    hex: "#909295",
    surface: "Smooth",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t009-gr230",
    friendlyName: "High Gloss Light Gray",
    officialName: "RAL 7035 Gray 90 Gloss",
    code: "T009-GR230",
    group: "grays",
    hex: "#CDCECE",
    surface: "Smooth",
    gloss: "90 (±5)",
    glossLevel: 9,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Smooth · Gloss 90",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c241-gr305",
    friendlyName: "Bay Gray Texture",
    officialName: "Bay Gray Texture",
    code: "C241-GR305",
    group: "grays",
    hex: "#8A8685",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t243-gr301",
    friendlyName: "Quartz Gray Texture",
    officialName: "Quartz Gray Texture",
    code: "T243-GR301",
    group: "grays",
    hex: "#D3CFCD",
    surface: "Texture",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t243-gr522",
    friendlyName: "Flint Gray Texture",
    officialName: "Flint Gray Texture",
    code: "T243-GR522",
    group: "grays",
    hex: "#ABACAC",
    surface: "Texture",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t241-gr11",
    friendlyName: "Platinum Gray Texture",
    officialName: "Platinum Gray Texture",
    code: "T241-GR11",
    group: "grays",
    hex: "#C1BFB8",
    surface: "Texture",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    statLine: "Texture · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t375-bk07",
    friendlyName: "Copper Vein",
    officialName: "Copper Vein",
    code: "T375-BK07",
    group: "specialty",
    hex: "#353337",
    surface: "Vein",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Vein · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t375-bk10",
    friendlyName: "Gold Vein",
    officialName: "Gold Vein",
    code: "T375-BK10",
    group: "specialty",
    hex: "#343334",
    surface: "Vein",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Vein · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t375-bk26",
    friendlyName: "Silver Vein",
    officialName: "Silver Vein",
    code: "T375-BK26",
    group: "specialty",
    hex: "#333336",
    surface: "Vein",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Vein · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t075-wh34",
    friendlyName: "Black and White Vein",
    officialName: "Black/White Texture",
    code: "T075-WH34",
    group: "specialty",
    hex: "#C7CDD4",
    surface: "Vein",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Vein · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t075-bk211",
    friendlyName: "Exterior Copper Vein",
    officialName: "Copper Vein Exterior",
    code: "T075-BK211",
    group: "specialty",
    hex: "#252629",
    surface: "Vein",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Vein · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t064-br24",
    friendlyName: "Bronze Hammertone",
    officialName: "Bronze Hammertone",
    code: "T064-BR24",
    group: "specialty",
    hex: "#7C6350",
    surface: "Hammertone",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammertone · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t064-gr660",
    friendlyName: "Gray Hammertone",
    officialName: "Gray Hammertone",
    code: "T064-GR660",
    group: "specialty",
    hex: "#44464A",
    surface: "Hammertone",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammertone · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t064-gr05",
    friendlyName: "Silver Hammertone",
    officialName: "Silver Hammertone",
    code: "T064-GR05",
    group: "specialty",
    hex: "#66676B",
    surface: "Hammertone",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammertone · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t064-bl95",
    friendlyName: "Blue Hammertone",
    officialName: "Blue Hammertone",
    code: "T064-BL95",
    group: "specialty",
    hex: "#223E5B",
    surface: "Hammertone",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammertone · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t064-gn81",
    friendlyName: "Green Hammertone",
    officialName: "Green Hammertone",
    code: "T064-GN81",
    group: "specialty",
    hex: "#275150",
    surface: "Hammertone",
    gloss: "40 (±5)",
    glossLevel: 4,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Hammertone · Gloss 40",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t091-gr309",
    friendlyName: "Mock Rock",
    officialName: "Mock Rock Texture",
    code: "T091-GR309",
    group: "specialty",
    hex: "#6C6D6D",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c292-gr494",
    friendlyName: "Steel Gray Texture",
    officialName: "Steel Gray Texture",
    code: "C292-GR494",
    group: "specialty",
    hex: "#373E43",
    surface: "Special",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Special · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c081-bk176",
    friendlyName: "Black Wrinkle",
    officialName: "Black Wrinkle",
    code: "C081-BK176",
    group: "specialty",
    hex: "#32373F",
    surface: "Wrinkle",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester HAA",
    statLine: "Wrinkle · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t391-bg290",
    friendlyName: "Bronze Metallic Texture",
    officialName: "Bronze Metallic Texture",
    code: "T391-BG290",
    group: "specialty",
    hex: "#948D88",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t391-gr1031",
    friendlyName: "Silver Metallic Texture",
    officialName: "Silver Metallic Texture",
    code: "T391-GR1031",
    group: "specialty",
    hex: "#747579",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t353-yl02",
    friendlyName: "Brass Metallic",
    officialName: "Brass Metallic 30 Gloss",
    code: "T353-YL02",
    group: "specialty",
    hex: "#73623E",
    surface: "Metallic",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Metallic · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t353-gr06",
    friendlyName: "Satin Silver Metallic",
    officialName: "Silver Metallic 30 Gloss",
    code: "T353-GR06",
    group: "specialty",
    hex: "#A1A09E",
    surface: "Metallic",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Metallic · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c356-gr1342",
    friendlyName: "Semi-Gloss Silver Metallic",
    officialName: "Silver Metallic 60 Gloss",
    code: "C356-GR1342",
    group: "specialty",
    hex: "#94918F",
    surface: "Metallic",
    gloss: "60 (±5)",
    glossLevel: 6,
    cure: "Interior/400°F",
    powder: "Polyester HAA",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Metallic · Gloss 60",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t358-gr539",
    friendlyName: "Chrome Metallic",
    officialName: "Chrome Metallic 80 Gloss",
    code: "T358-GR539",
    group: "specialty",
    hex: "#85817F",
    surface: "Metallic",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Metallic · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t357-gr105",
    friendlyName: "Gloss Silver Metallic",
    officialName: "Silver Metallic 70 Gloss",
    code: "T357-GR105",
    group: "specialty",
    hex: "#81848C",
    surface: "Metallic",
    gloss: "70 (±5)",
    glossLevel: 7,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Metallic · Gloss 70",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t353-gr938",
    friendlyName: "Bright Silver Metallic",
    officialName: "Silver Metallic 30 Gloss",
    code: "T353-GR938",
    group: "specialty",
    hex: "#747577",
    surface: "Metallic",
    gloss: "30 (±5)",
    glossLevel: 3,
    cure: "Interior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "To maintain the appearance of exterior metallic finishes a clear topcoat is recommended.",
    statLine: "Metallic · Gloss 30",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t026-br340",
    friendlyName: "Statuary Bronze",
    officialName: "Statuary Bronze 60 Gloss",
    code: "T026-BR340",
    group: "specialty",
    hex: "#444145",
    surface: "Pearlescent",
    gloss: "60 (±5)",
    glossLevel: 6,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Pearlescent · Gloss 60",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t291-br251",
    friendlyName: "Oil Rubbed Bronze",
    officialName: "Oil Rubbed Bronze Texture",
    code: "T291-BR251",
    group: "specialty",
    hex: "#403D3E",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t022-br189",
    friendlyName: "Oil Bronze",
    officialName: "Oil Bronze 20 Gloss",
    code: "T022-BR189",
    group: "specialty",
    hex: "#323134",
    surface: "Pearlescent",
    gloss: "20 (±5)",
    glossLevel: 2,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Pearlescent · Gloss 20",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t028-gr02",
    friendlyName: "Steel Gray",
    officialName: "Steel Gray 80 Gloss",
    code: "T028-GR02",
    group: "specialty",
    hex: "#3B3B3E",
    surface: "Pearlescent",
    gloss: "80 (±5)",
    glossLevel: 8,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Pearlescent · Gloss 80",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t025-br01",
    friendlyName: "Pearlescent Bronze",
    officialName: "Bronze 50 Gloss",
    code: "T025-BR01",
    group: "specialty",
    hex: "#3A3534",
    surface: "Pearlescent",
    gloss: "50 (±5)",
    glossLevel: 5,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Pearlescent · Gloss 50",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t021-gn508",
    friendlyName: "Jade Green",
    officialName: "Jade Green",
    code: "T021-GN508",
    group: "specialty",
    hex: "#7F9259",
    surface: "Pearlescent",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Pearlescent · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t021-og91",
    friendlyName: "Ember Orange",
    officialName: "Ember Orange",
    code: "T021-OG91",
    group: "specialty",
    hex: "#E06C4F",
    surface: "Pearlescent",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    cardinalNote: "Product exhibiting a metallic appearance and formulated for exterior use without requiring a clear topcoat.",
    statLine: "Pearlescent · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "c291-gn20",
    friendlyName: "Patina",
    officialName: "Patina Texture",
    code: "C291-GN20",
    group: "specialty",
    hex: "#405458",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/350°F",
    powder: "Polyester HAA",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t091-gn57",
    friendlyName: "Verdigris",
    officialName: "Verdigris Texture",
    code: "T091-GN57",
    group: "specialty",
    hex: "#304144",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
  {
    id: "t091-br47",
    friendlyName: "Rust",
    officialName: "Rust Texture",
    code: "T091-BR47",
    group: "specialty",
    hex: "#433736",
    surface: "Special",
    gloss: "10 (±5)",
    glossLevel: 1,
    cure: "Exterior/400°F",
    powder: "Polyester TGIC",
    statLine: "Special · Gloss 10",
    source: SOURCES.cardinalCard,
    swatch: POST_SWATCH,
  },
];

/** On the card but not offered for outdoor posts: Cardinal's own ** footnote says these are for interior use only
 * (this includes the four primers). The two Clear topcoats (T209-CL01 / T909-CL05 / T008-CL07 and T002-CL02) are
 * not colors and are also left out. Kept here so the choice is visible and reversible. */
export const POST_COLORS_NOT_SHOWN: { code: string; officialName: string; reason: string }[] = [
  { code: "H308-BL03", officialName: "Blue 80 Gloss", reason: "Card footnote **: interior products only" },
  { code: "E311-BK04", officialName: "Black Hammer Low Gloss", reason: "Card footnote **: interior products only" },
  { code: "E305-GR533", officialName: "Gray Primer", reason: "Card footnote **: interior products only" },
  { code: "E305-WH243", officialName: "White Primer", reason: "Card footnote **: interior products only" },
  { code: "H304-GR312", officialName: "Gray Anti-Gassing Primer", reason: "Card footnote **: interior products only" },
  { code: "E396-GR1372", officialName: "Gray Zinc Rich Primer", reason: "Card footnote **: interior products only" },
  { code: "H308-WH25", officialName: "H308-WH25", reason: "Card footnote **: interior products only" },
  { code: "H303-WH16", officialName: "Antique White 30 Gloss", reason: "Card footnote **: interior products only" },
  { code: "H309-WH27", officialName: "Frost White 90 Gloss", reason: "Card footnote **: interior products only" },
  { code: "E141-BK19", officialName: "Black Texture", reason: "Card footnote **: interior products only" },
  { code: "E300-BK11", officialName: "Black Flat", reason: "Card footnote **: interior products only" },
  { code: "E300-BK147", officialName: "Black Flat", reason: "Card footnote **: interior products only" },
  { code: "H302-BK46", officialName: "Black 20 Gloss", reason: "Card footnote **: interior products only" },
  { code: "H305-GR10", officialName: "Light Gunmetal Gray 50 Gloss", reason: "Card footnote **: interior products only" },
  { code: "H392-WH469", officialName: "ESD White", reason: "Card footnote **: interior products only" },
  { code: "H392-BK116", officialName: "ESD Black", reason: "Card footnote **: interior products only" },
  { code: "H391-GR596", officialName: "ESD Gray", reason: "Card footnote **: interior products only" },
  { code: "E381-BK173", officialName: "Black Wrinkle", reason: "Card footnote **: interior products only" },
];

